export const ADD_ABSENCE_REQUEST = "ADD_ABSENCE_REQUEST";
export const ADD_ABSENCE_SUCCESS = "ADD_ABSENCE_SUCCESS";
export const ADD_ABSENCE_FAIL = "ADD_ABSENCE_FAIL";

export const UPDATE_ABSENCE_REQUEST = "UPDATE_ABSENCE_REQUEST";
export const UPDATE_ABSENCE_SUCCESS = "UPDATE_ABSENCE_SUCCESS";
export const UPDATE_ABSENCE_FAIL = "UPDATE_ABSENCE_FAIL";

export const DELETE_ABSENCE_REQUEST = "DELETE_ABSENCE_REQUEST";
export const DELETE_ABSENCE_SUCCESS = "DELETE_ABSENCE_SUCCESS";
export const DELETE_ABSENCE_FAIL = "DELETE_ABSENCE_FAIL";

export const GET_ABSENCE_REQUEST = "GET_ABSENCE_REQUEST";
export const GET_ABSENCE_SUCCESS = "GET_ABSENCE_SUCCESS";
export const GET_ABSENCE_FAIL = "GET_ABSENCE_FAIL";

export const GET_ABSENCES_BY_DATES_REQUEST = "GET_ABSENCES_BY_DATES_REQUEST";
export const GET_ABSENCES_BY_DATES_SUCCESS = "GET_ABSENCES_BY_DATES_SUCCESS";
export const GET_ABSENCES_BY_DATES_FAIL = "GET_ABSENCES_BY_DATES_FAIL";

export const GET_ABSENCES_BY_EMPLOYEE_REQUEST =
  "GET_ABSENCES_BY_EMPLOYEE_REQUEST";
export const GET_ABSENCES_BY_EMPLOYEE_SUCCESS =
  "GET_ABSENCES_BY_EMPLOYEE_SUCCESS";
export const GET_ABSENCES_BY_EMPLOYEE_FAIL = "GET_ABSENCES_BY_EMPLOYEE_FAIL";
