export const ADD_APPRAISAL_REQUEST = "ADD_APPRAISAL_REQUEST";
export const ADD_APPRAISAL_SUCCESS = "ADD_APPRAISAL_SUCCESS";
export const ADD_APPRAISAL_FAIL = "ADD_APPRAISAL_FAIL";

export const UPDATE_APPRAISAL_REQUEST = "UPDATE_APPRAISAL_REQUEST";
export const UPDATE_APPRAISAL_SUCCESS = "UPDATE_APPRAISAL_SUCCESS";
export const UPDATE_APPRAISAL_FAIL = "UPDATE_APPRAISAL_FAIL";

export const GET_APPRAISAL_REQUEST = "GET_APPRAISAL_REQUEST";
export const GET_APPRAISAL_SUCCESS = "GET_APPRAISAL_SUCCESS";
export const GET_APPRAISAL_FAIL = "GET_APPRAISAL_FAIL";

export const GET_APPRAISALS_REQUEST = "GET_APPRAISALS_REQUEST";
export const GET_APPRAISALS_SUCCESS = "GET_APPRAISALS_SUCCESS";
export const GET_APPRAISALS_FAIL = "GET_APPRAISALS_FAIL";

export const DELETE_APPRAISAL_REQUEST = "DELETE_APPRAISAL_REQUEST";
export const DELETE_APPRAISAL_SUCCESS = "DELETE_APPRAISAL_SUCCESS";
export const DELETE_APPRAISAL_FAIL = "DELETE_APPRAISAL_FAIL";
