export const ADD_COMMUNICATION_REQUEST = "ADD_COMMUNICATION_REQUEST";
export const ADD_COMMUNICATION_SUCCESS = "ADD_COMMUNICATION_SUCCESS";
export const ADD_COMMUNICATION_FAIL = "ADD_COMMUNICATION_FAIL";

export const UPDATE_COMMUNICATION_REQUEST = "UPDATE_COMMUNICATION_REQUEST";
export const UPDATE_COMMUNICATION_SUCCESS = "UPDATE_COMMUNICATION_SUCCESS";
export const UPDATE_COMMUNICATION_FAIL = "UPDATE_COMMUNICATION_FAIL";

export const GET_COMMUNICATION_REQUEST = "GET_COMMUNICATION_REQUEST";
export const GET_COMMUNICATION_SUCCESS = "GET_COMMUNICATION_SUCCESS";
export const GET_COMMUNICATION_FAIL = "GET_COMMUNICATION_FAIL";

export const GET_COMMUNICATIONS_REQUEST = "GET_COMMUNICATIONS_REQUEST";
export const GET_COMMUNICATIONS_SUCCESS = "GET_COMMUNICATIONS_SUCCESS";
export const GET_COMMUNICATIONS_FAIL = "GET_COMMUNICATIONS_FAIL";

export const DELETE_COMMUNICATION_REQUEST = "DELETE_COMMUNICATION_REQUEST";
export const DELETE_COMMUNICATION_SUCCESS = "DELETE_COMMUNICATION_SUCCESS";
export const DELETE_COMMUNICATION_FAIL = "DELETE_COMMUNICATION_FAIL";
