export const ADD_DAILY_OBSERVATION_REQUEST = "ADD_DAILY_OBSERVATION_REQUEST";
export const ADD_DAILY_OBSERVATION_SUCCESS = "ADD_DAILY_OBSERVATION_SUCCESS";
export const ADD_DAILY_OBSERVATION_FAIL = "ADD_DAILY_OBSERVATION_FAIL";

export const UPDATE_DAILY_OBSERVATION_REQUEST =
  "UPDATE_DAILY_OBSERVATION_REQUEST";
export const UPDATE_DAILY_OBSERVATION_SUCCESS =
  "UPDATE_DAILY_OBSERVATION_SUCCESS";
export const UPDATE_DAILY_OBSERVATION_FAIL = "UPDATE_DAILY_OBSERVATION_FAIL";

export const GET_DAILY_OBSERVATION_REQUEST = "GET_DAILY_OBSERVATION_REQUEST";
export const GET_DAILY_OBSERVATION_SUCCESS = "GET_DAILY_OBSERVATION_SUCCESS";
export const GET_DAILY_OBSERVATION_FAIL = "GET_DAILY_OBSERVATION_FAIL";

export const GET_DAILY_OBSERVATIONS_REQUEST = "GET_DAILY_OBSERVATIONS_REQUEST";
export const GET_DAILY_OBSERVATIONS_SUCCESS = "GET_DAILY_OBSERVATIONS_SUCCESS";
export const GET_DAILY_OBSERVATIONS_FAIL = "GET_DAILY_OBSERVATIONS_FAIL";

export const DELETE_DAILY_OBSERVATION_REQUEST =
  "DELETE_DAILY_OBSERVATION_REQUEST";
export const DELETE_DAILY_OBSERVATION_SUCCESS =
  "DELETE_DAILY_OBSERVATION_SUCCESS";
export const DELETE_DAILY_OBSERVATION_FAIL = "DELETE_DAILY_OBSERVATION_FAIL";
