export const ADD_DIARY_ENTRY_REQUEST = "ADD_DIARY_ENTRY_REQUEST";
export const ADD_DIARY_ENTRY_SUCCESS = "ADD_DIARY_ENTRY_SUCCESS";
export const ADD_DIARY_ENTRY_FAIL = "ADD_DIARY_ENTRY_FAIL";

export const UPDATE_DIARY_ENTRY_REQUEST = "UPDATE_DIARY_ENTRY_REQUEST";
export const UPDATE_DIARY_ENTRY_SUCCESS = "UPDATE_DIARY_ENTRY_SUCCESS";
export const UPDATE_DIARY_ENTRY_FAIL = "UPDATE_DIARY_ENTRY_FAIL";

export const GET_DIARY_ENTRY_REQUEST = "GET_DIARY_ENTRY_REQUEST";
export const GET_DIARY_ENTRY_SUCCESS = "GET_DIARY_ENTRY_SUCCESS";
export const GET_DIARY_ENTRY_FAIL = "GET_DIARY_ENTRY_FAIL";

export const GET_DIARY_ENTRIES_REQUEST = "GET_DIARY_ENTRIES_REQUEST";
export const GET_DIARY_ENTRIES_SUCCESS = "GET_DIARY_ENTRIES_SUCCESS";
export const GET_DIARY_ENTRIES_FAIL = "GET_DIARY_ENTRIES_FAIL";

export const DELETE_DIARY_ENTRY_REQUEST = "DELETE_DIARY_ENTRY_REQUEST";
export const DELETE_DIARY_ENTRY_SUCCESS = "DELETE_DIARY_ENTRY_SUCCESS";
export const DELETE_DIARY_ENTRY_FAIL = "DELETE_DIARY_ENTRY_FAIL";
