export const ADD_HANDOVER_REQUEST = "ADD_HANDOVER_REQUEST";
export const ADD_HANDOVER_SUCCESS = "ADD_HANDOVER_SUCCESS";
export const ADD_HANDOVER_FAIL = "ADD_HANDOVER_FAIL";

export const UPDATE_HANDOVER_REQUEST = "UPDATE_HANDOVER_REQUEST";
export const UPDATE_HANDOVER_SUCCESS = "UPDATE_HANDOVER_SUCCESS";
export const UPDATE_HANDOVER_FAIL = "UPDATE_HANDOVER_FAIL";

export const GET_HANDOVER_REQUEST = "GET_HANDOVER_REQUEST";
export const GET_HANDOVER_SUCCESS = "GET_HANDOVER_SUCCESS";
export const GET_HANDOVER_FAIL = "GET_HANDOVER_FAIL";

export const GET_HANDOVERS_REQUEST = "GET_HANDOVERS_REQUEST";
export const GET_HANDOVERS_SUCCESS = "GET_HANDOVERS_SUCCESS";
export const GET_HANDOVERS_FAIL = "GET_HANDOVERS_FAIL";

export const DELETE_HANDOVER_REQUEST = "DELETE_HANDOVER_REQUEST";
export const DELETE_HANDOVER_SUCCESS = "DELETE_HANDOVER_SUCCESS";
export const DELETE_HANDOVER_FAIL = "DELETE_HANDOVER_FAIL";
