export const ADD_SERVICE_USER_REQUEST = "ADD_SERVICE_USER_REQUEST";
export const ADD_SERVICE_USER_SUCCESS = "ADD_SERVICE_USER_SUCCESS";
export const ADD_SERVICE_USER_FAIL = "ADD_SERVICE_USER_FAIL";

export const UPDATE_SERVICE_USER_REQUEST = "UPDATE_SERVICE_USER_REQUEST";
export const UPDATE_SERVICE_USER_SUCCESS = "UPDATE_SERVICE_USER_SUCCESS";
export const UPDATE_SERVICE_USER_FAIL = "UPDATE_SERVICE_USER_FAIL";

export const GET_SERVICE_USER_REQUEST = "GET_SERVICE_USER_REQUEST";
export const GET_SERVICE_USER_SUCCESS = "GET_SERVICE_USER_SUCCESS";
export const GET_SERVICE_USER_FAIL = "GET_SERVICE_USER_FAIL";

export const GET_SERVICE_USERS_REQUEST = "GET_SERVICE_USERS_REQUEST";
export const GET_SERVICE_USERS_SUCCESS = "GET_SERVICE_USERS_SUCCESS";
export const GET_SERVICE_USERS_FAIL = "GET_SERVICE_USERS_FAIL";

export const DELETE_SERVICE_USER_REQUEST = "DELETE_SERVICE_USER_REQUEST";
export const DELETE_SERVICE_USER_SUCCESS = "DELETE_SERVICE_USER_SUCCESS";
export const DELETE_SERVICE_USER_FAIL = "DELETE_SERVICE_USER_FAIL";
