export const ADD_SUPERVISION_REQUEST = "ADD_SUPERVISION_REQUEST";
export const ADD_SUPERVISION_SUCCESS = "ADD_SUPERVISION_SUCCESS";
export const ADD_SUPERVISION_FAIL = "ADD_SUPERVISION_FAIL";

export const UPDATE_SUPERVISION_REQUEST = "UPDATE_SUPERVISION_REQUEST";
export const UPDATE_SUPERVISION_SUCCESS = "UPDATE_SUPERVISION_SUCCESS";
export const UPDATE_SUPERVISION_FAIL = "UPDATE_SUPERVISION_FAIL";

export const GET_SUPERVISION_REQUEST = "GET_SUPERVISION_REQUEST";
export const GET_SUPERVISION_SUCCESS = "GET_SUPERVISION_SUCCESS";
export const GET_SUPERVISION_FAIL = "GET_SUPERVISION_FAIL";

export const GET_LATEST_SUPERVISION_REQUEST = "GET_LATEST_SUPERVISION_REQUEST";
export const GET_LATEST_SUPERVISION_SUCCESS = "GET_LATEST_SUPERVISION_SUCCESS";
export const GET_LATEST_SUPERVISION_FAIL = "GET_LATEST_SUPERVISION_FAIL";

export const GET_SUPERVISIONS_REQUEST = "GET_SUPERVISIONS_REQUEST";
export const GET_SUPERVISIONS_SUCCESS = "GET_SUPERVISIONS_SUCCESS";
export const GET_SUPERVISIONS_FAIL = "GET_SUPERVISIONS_FAIL";

export const DELETE_SUPERVISION_REQUEST = "DELETE_SUPERVISION_REQUEST";
export const DELETE_SUPERVISION_SUCCESS = "DELETE_SUPERVISION_SUCCESS";
export const DELETE_SUPERVISION_FAIL = "DELETE_SUPERVISION_FAIL";
