export const ADD_WORKING_SHIFT_REQUEST = "ADD_WORKING_SHIFT_REQUEST";
export const ADD_WORKING_SHIFT_SUCCESS = "ADD_WORKING_SHIFT_SUCCESS";
export const ADD_WORKING_SHIFT_FAIL = "ADD_WORKING_SHIFT_FAIL";

export const UPDATE_WORKING_SHIFT_REQUEST = "UPDATE_WORKING_SHIFT_REQUEST";
export const UPDATE_WORKING_SHIFT_SUCCESS = "UPDATE_WORKING_SHIFT_SUCCESS";
export const UPDATE_WORKING_SHIFT_FAIL = "UPDATE_WORKING_SHIFT_FAIL";

export const GET_WORKING_SHIFT_REQUEST = "GET_WORKING_SHIFT_REQUEST";
export const GET_WORKING_SHIFT_SUCCESS = "GET_WORKING_SHIFT_SUCCESS";
export const GET_WORKING_SHIFT_FAIL = "GET_WORKING_SHIFT_FAIL";

export const GET_WORKING_SHIFTS_REQUEST = "GET_WORKING_SHIFTS_REQUEST";
export const GET_WORKING_SHIFTS_SUCCESS = "GET_WORKING_SHIFTS_SUCCESS";
export const GET_WORKING_SHIFTS_FAIL = "GET_WORKING_SHIFTS_FAIL";

export const GET_WORKING_SHIFTS_BY_EMPLOYEE_BY_DAY_REQUEST =
  "GET_WORKING_SHIFTS_BY_EMPLOYEE_BY_DAY_REQUEST";
export const GET_WORKING_SHIFTS_BY_EMPLOYEE_BY_DAY_SUCCESS =
  "GET_WORKING_SHIFTS_BY_EMPLOYEE_BY_DAY_SUCCESS";
export const GET_WORKING_SHIFTS_BY_EMPLOYEE_BY_DAY_FAIL =
  "GET_WORKING_SHIFTS_BY_EMPLOYEE_BY_DAY_FAIL";

export const GET_WORKING_SHIFTS_BY_INTERVAL_REQUEST =
  "GET_WORKING_SHIFTS_BY_INTERVAL_REQUEST";
export const GET_WORKING_SHIFTS_BY_INTERVAL_SUCCESS =
  "GET_WORKING_SHIFTS_BY_INTERVAL_SUCCESS";
export const GET_WORKING_SHIFTS_BY_INTERVAL_FAIL =
  "GET_WORKING_SHIFTS_BY_INTERVAL_FAIL";

export const DELETE_WORKING_SHIFT_REQUEST = "DELETE_WORKING_SHIFT_REQUEST";
export const DELETE_WORKING_SHIFT_SUCCESS = "DELETE_WORKING_SHIFT_SUCCESS";
export const DELETE_WORKING_SHIFT_FAIL = "DELETE_WORKING_SHIFT_FAIL";
