export const ADD_WORKING_STATUS_REQUEST = "ADD_WORKING_STATUS_REQUEST";
export const ADD_WORKING_STATUS_SUCCESS = "ADD_WORKING_STATUS_SUCCESS";
export const ADD_WORKING_STATUS_FAIL = "ADD_WORKING_STATUS_FAIL";

export const UPDATE_WORKING_STATUS_REQUEST = "UPDATE_WORKING_STATUS_REQUEST";
export const UPDATE_WORKING_STATUS_SUCCESS = "UPDATE_WORKING_STATUS_SUCCESS";
export const UPDATE_WORKING_STATUS_FAIL = "UPDATE_WORKING_STATUS_FAIL";

export const GET_WORKING_STATUS_REQUEST = "GET_WORKING_STATUS_REQUEST";
export const GET_WORKING_STATUS_SUCCESS = "GET_WORKING_STATUS_SUCCESS";
export const GET_WORKING_STATUS_FAIL = "GET_WORKING_STATUS_FAIL";

export const GET_WORKING_STATUSES_REQUEST = "GET_WORKING_STATUSES_REQUEST";
export const GET_WORKING_STATUSES_SUCCESS = "GET_WORKING_STATUSES_SUCCESS";
export const GET_WORKING_STATUSES_FAIL = "GET_WORKING_STATUSES_FAIL";

export const DELETE_WORKING_STATUS_REQUEST = "DELETE_WORKING_STATUS_REQUEST";
export const DELETE_WORKING_STATUS_SUCCESS = "DELETE_WORKING_STATUS_SUCCESS";
export const DELETE_WORKING_STATUS_FAIL = "DELETE_WORKING_STATUS_FAIL";
